export type Community = {
  slug: string
  name: string
  area: string
  type: 'mixed' | 'apartments' | 'villas'
  isFreehold: boolean
  avgPricePerSqft: number
  medianPrice: number
  totalUnits: number
  apartments: number
  villas: number
  grossYield: number
  transactions30d: number
  upcomingSupply: number
  momChange: number // %
  avgDaysOnMarket: number
}

export const MOCK_COMMUNITIES: Community[] = [
  {
    slug: 'dubai-marina',
    name: 'Dubai Marina',
    area: 'West Dubai',
    type: 'apartments',
    isFreehold: true,
    avgPricePerSqft: 1950,
    medianPrice: 6200000,
    totalUnits: 44800,
    apartments: 44200,
    villas: 600,
    grossYield: 5.6,
    transactions30d: 312,
    upcomingSupply: 1200,
    momChange: 1.8,
    avgDaysOnMarket: 42,
  },
  {
    slug: 'downtown-dubai',
    name: 'Downtown Dubai',
    area: 'Central',
    type: 'apartments',
    isFreehold: true,
    avgPricePerSqft: 2650,
    medianPrice: 3800000,
    totalUnits: 22400,
    apartments: 22200,
    villas: 200,
    grossYield: 4.8,
    transactions30d: 198,
    upcomingSupply: 850,
    momChange: 2.4,
    avgDaysOnMarket: 38,
  },
  {
    slug: 'palm-jumeirah',
    name: 'Palm Jumeirah',
    area: 'West Dubai',
    type: 'mixed',
    isFreehold: true,
    avgPricePerSqft: 3200,
    medianPrice: 6500000,
    totalUnits: 28600,
    apartments: 19000,
    villas: 9600,
    grossYield: 4.2,
    transactions30d: 145,
    upcomingSupply: 420,
    momChange: 3.1,
    avgDaysOnMarket: 55,
  },
  {
    slug: 'jumeirah-village-circle',
    name: 'Jumeirah Village Circle',
    area: 'South Dubai',
    type: 'mixed',
    isFreehold: true,
    avgPricePerSqft: 1050,
    medianPrice: 850000,
    totalUnits: 38500,
    apartments: 32000,
    villas: 6500,
    grossYield: 7.8,
    transactions30d: 488,
    upcomingSupply: 4200,
    momChange: 0.9,
    avgDaysOnMarket: 31,
  },
  {
    slug: 'business-bay',
    name: 'Business Bay',
    area: 'Central',
    type: 'apartments',
    isFreehold: true,
    avgPricePerSqft: 1750,
    medianPrice: 1800000,
    totalUnits: 34200,
    apartments: 33800,
    villas: 400,
    grossYield: 5.9,
    transactions30d: 276,
    upcomingSupply: 1800,
    momChange: 1.4,
    avgDaysOnMarket: 36,
  },
  {
    slug: 'jumeirah-lake-towers',
    name: 'Jumeirah Lake Towers',
    area: 'West Dubai',
    type: 'apartments',
    isFreehold: true,
    avgPricePerSqft: 1350,
    medianPrice: 1100000,
    totalUnits: 52000,
    apartments: 51500,
    villas: 500,
    grossYield: 6.5,
    transactions30d: 221,
    upcomingSupply: 0,
    momChange: 0.6,
    avgDaysOnMarket: 44,
  },
  {
    slug: 'arabian-ranches',
    name: 'Arabian Ranches',
    area: 'Dubailand',
    type: 'villas',
    isFreehold: true,
    avgPricePerSqft: 1650,
    medianPrice: 4200000,
    totalUnits: 9800,
    apartments: 200,
    villas: 9600,
    grossYield: 4.5,
    transactions30d: 88,
    upcomingSupply: 0,
    momChange: 2.2,
    avgDaysOnMarket: 62,
  },
  {
    slug: 'dubai-hills-estate',
    name: 'Dubai Hills Estate',
    area: 'South Dubai',
    type: 'mixed',
    isFreehold: true,
    avgPricePerSqft: 1950,
    medianPrice: 4800000,
    totalUnits: 14200,
    apartments: 7800,
    villas: 6400,
    grossYield: 4.7,
    transactions30d: 142,
    upcomingSupply: 2100,
    momChange: 1.9,
    avgDaysOnMarket: 48,
  },
  {
    slug: 'sports-city',
    name: 'Dubai Sports City',
    area: 'Dubailand',
    type: 'apartments',
    isFreehold: true,
    avgPricePerSqft: 880,
    medianPrice: 680000,
    totalUnits: 21600,
    apartments: 20800,
    villas: 800,
    grossYield: 8.1,
    transactions30d: 134,
    upcomingSupply: 600,
    momChange: 0.4,
    avgDaysOnMarket: 38,
  },
  {
    slug: 'motor-city',
    name: 'Motor City',
    area: 'Dubailand',
    type: 'mixed',
    isFreehold: true,
    avgPricePerSqft: 950,
    medianPrice: 780000,
    totalUnits: 12400,
    apartments: 9800,
    villas: 2600,
    grossYield: 7.2,
    transactions30d: 96,
    upcomingSupply: 200,
    momChange: 0.7,
    avgDaysOnMarket: 41,
  },
  {
    slug: 'international-city',
    name: 'International City',
    area: 'East Dubai',
    type: 'apartments',
    isFreehold: true,
    avgPricePerSqft: 620,
    medianPrice: 450000,
    totalUnits: 30200,
    apartments: 30200,
    villas: 0,
    grossYield: 10.2,
    transactions30d: 189,
    upcomingSupply: 0,
    momChange: -0.3,
    avgDaysOnMarket: 28,
  },
  {
    slug: 'mirdif',
    name: 'Mirdif',
    area: 'East Dubai',
    type: 'villas',
    isFreehold: false,
    avgPricePerSqft: 820,
    medianPrice: 2100000,
    totalUnits: 8900,
    apartments: 1200,
    villas: 7700,
    grossYield: 5.8,
    transactions30d: 54,
    upcomingSupply: 0,
    momChange: 0.2,
    avgDaysOnMarket: 68,
  },
  {
    slug: 'difc',
    name: 'DIFC',
    area: 'Central',
    type: 'apartments',
    isFreehold: true,
    avgPricePerSqft: 2800,
    medianPrice: 2800000,
    totalUnits: 4200,
    apartments: 4200,
    villas: 0,
    grossYield: 4.1,
    transactions30d: 38,
    upcomingSupply: 300,
    momChange: 2.8,
    avgDaysOnMarket: 51,
  },
  {
    slug: 'discovery-gardens',
    name: 'Discovery Gardens',
    area: 'West Dubai',
    type: 'apartments',
    isFreehold: true,
    avgPricePerSqft: 650,
    medianPrice: 450000,
    totalUnits: 26400,
    apartments: 26400,
    villas: 0,
    grossYield: 9.5,
    transactions30d: 142,
    upcomingSupply: 0,
    momChange: -0.1,
    avgDaysOnMarket: 30,
  },
  {
    slug: 'al-furjan',
    name: 'Al Furjan',
    area: 'West Dubai',
    type: 'mixed',
    isFreehold: true,
    avgPricePerSqft: 1150,
    medianPrice: 1900000,
    totalUnits: 11800,
    apartments: 7200,
    villas: 4600,
    grossYield: 6.2,
    transactions30d: 108,
    upcomingSupply: 1400,
    momChange: 1.1,
    avgDaysOnMarket: 40,
  },
  {
    slug: 'damac-hills',
    name: 'DAMAC Hills',
    area: 'Dubailand',
    type: 'mixed',
    isFreehold: true,
    avgPricePerSqft: 1250,
    medianPrice: 2800000,
    totalUnits: 18200,
    apartments: 9400,
    villas: 8800,
    grossYield: 5.4,
    transactions30d: 118,
    upcomingSupply: 1800,
    momChange: 1.5,
    avgDaysOnMarket: 47,
  },
  {
    slug: 'town-square',
    name: 'Town Square',
    area: 'South Dubai',
    type: 'mixed',
    isFreehold: true,
    avgPricePerSqft: 980,
    medianPrice: 950000,
    totalUnits: 14600,
    apartments: 8800,
    villas: 5800,
    grossYield: 7.5,
    transactions30d: 132,
    upcomingSupply: 3200,
    momChange: 0.8,
    avgDaysOnMarket: 35,
  },
  {
    slug: 'dubai-creek-harbour',
    name: 'Dubai Creek Harbour',
    area: 'East Dubai',
    type: 'apartments',
    isFreehold: true,
    avgPricePerSqft: 1850,
    medianPrice: 2200000,
    totalUnits: 9800,
    apartments: 9600,
    villas: 200,
    grossYield: 5.2,
    transactions30d: 94,
    upcomingSupply: 6400,
    momChange: 2.6,
    avgDaysOnMarket: 44,
  },
  {
    slug: 'sobha-hartland',
    name: 'Sobha Hartland',
    area: 'MBR City',
    type: 'mixed',
    isFreehold: true,
    avgPricePerSqft: 2100,
    medianPrice: 3400000,
    totalUnits: 6200,
    apartments: 4800,
    villas: 1400,
    grossYield: 5.1,
    transactions30d: 76,
    upcomingSupply: 2200,
    momChange: 3.4,
    avgDaysOnMarket: 52,
  },
  {
    slug: 'jumeirah-beach-residence',
    name: 'Jumeirah Beach Residence',
    area: 'West Dubai',
    type: 'apartments',
    isFreehold: true,
    avgPricePerSqft: 2050,
    medianPrice: 2800000,
    totalUnits: 16800,
    apartments: 16800,
    villas: 0,
    grossYield: 5.4,
    transactions30d: 148,
    upcomingSupply: 0,
    momChange: 1.6,
    avgDaysOnMarket: 46,
  },
  {
    slug: 'bluewaters-island',
    name: 'Bluewaters Island',
    area: 'West Dubai',
    type: 'apartments',
    isFreehold: true,
    avgPricePerSqft: 2950,
    medianPrice: 5200000,
    totalUnits: 3200,
    apartments: 3100,
    villas: 100,
    grossYield: 4.0,
    transactions30d: 28,
    upcomingSupply: 0,
    momChange: 2.9,
    avgDaysOnMarket: 64,
  },
  {
    slug: 'silicon-oasis',
    name: 'Dubai Silicon Oasis',
    area: 'East Dubai',
    type: 'apartments',
    isFreehold: true,
    avgPricePerSqft: 720,
    medianPrice: 580000,
    totalUnits: 18400,
    apartments: 18000,
    villas: 400,
    grossYield: 8.8,
    transactions30d: 112,
    upcomingSupply: 400,
    momChange: 0.5,
    avgDaysOnMarket: 32,
  },
  {
    slug: 'the-greens',
    name: 'The Greens',
    area: 'West Dubai',
    type: 'apartments',
    isFreehold: true,
    avgPricePerSqft: 1450,
    medianPrice: 1200000,
    totalUnits: 9200,
    apartments: 9200,
    villas: 0,
    grossYield: 6.8,
    transactions30d: 78,
    upcomingSupply: 0,
    momChange: 0.9,
    avgDaysOnMarket: 39,
  },
  {
    slug: 'emirates-hills',
    name: 'Emirates Hills',
    area: 'West Dubai',
    type: 'villas',
    isFreehold: true,
    avgPricePerSqft: 3100,
    medianPrice: 28000000,
    totalUnits: 1400,
    apartments: 0,
    villas: 1400,
    grossYield: 3.2,
    transactions30d: 12,
    upcomingSupply: 0,
    momChange: 4.1,
    avgDaysOnMarket: 112,
  },
  {
    slug: 'mudon',
    name: 'Mudon',
    area: 'Dubailand',
    type: 'villas',
    isFreehold: true,
    avgPricePerSqft: 1350,
    medianPrice: 3200000,
    totalUnits: 4800,
    apartments: 400,
    villas: 4400,
    grossYield: 5.1,
    transactions30d: 42,
    upcomingSupply: 600,
    momChange: 1.3,
    avgDaysOnMarket: 58,
  },
  {
    slug: 'tilal-al-ghaf',
    name: 'Tilal Al Ghaf',
    area: 'Dubailand',
    type: 'villas',
    isFreehold: true,
    avgPricePerSqft: 1650,
    medianPrice: 4800000,
    totalUnits: 6400,
    apartments: 800,
    villas: 5600,
    grossYield: 4.6,
    transactions30d: 64,
    upcomingSupply: 2800,
    momChange: 2.1,
    avgDaysOnMarket: 54,
  },
  {
    slug: 'emaar-south',
    name: 'Emaar South',
    area: 'South Dubai',
    type: 'mixed',
    isFreehold: true,
    avgPricePerSqft: 1100,
    medianPrice: 1200000,
    totalUnits: 8200,
    apartments: 4800,
    villas: 3400,
    grossYield: 7.1,
    transactions30d: 86,
    upcomingSupply: 3600,
    momChange: 1.2,
    avgDaysOnMarket: 38,
  },
  {
    slug: 'al-barsha',
    name: 'Al Barsha',
    area: 'West Dubai',
    type: 'mixed',
    isFreehold: false,
    avgPricePerSqft: 1050,
    medianPrice: 1400000,
    totalUnits: 7600,
    apartments: 5200,
    villas: 2400,
    grossYield: 6.0,
    transactions30d: 62,
    upcomingSupply: 0,
    momChange: 0.3,
    avgDaysOnMarket: 48,
  },
  {
    slug: 'remraam',
    name: 'Remraam',
    area: 'Dubailand',
    type: 'apartments',
    isFreehold: true,
    avgPricePerSqft: 780,
    medianPrice: 580000,
    totalUnits: 7200,
    apartments: 7200,
    villas: 0,
    grossYield: 8.4,
    transactions30d: 68,
    upcomingSupply: 0,
    momChange: 0.6,
    avgDaysOnMarket: 33,
  },
  {
    slug: 'city-walk',
    name: 'City Walk',
    area: 'Central',
    type: 'apartments',
    isFreehold: true,
    avgPricePerSqft: 2400,
    medianPrice: 3200000,
    totalUnits: 3800,
    apartments: 3800,
    villas: 0,
    grossYield: 4.5,
    transactions30d: 44,
    upcomingSupply: 200,
    momChange: 2.2,
    avgDaysOnMarket: 58,
  },
  {
    slug: 'the-springs',
    name: 'The Springs',
    area: 'Emirates Living',
    type: 'villas',
    isFreehold: true,
    avgPricePerSqft: 1400,
    medianPrice: 3200000,
    totalUnits: 3000,
    apartments: 0,
    villas: 3000,
    grossYield: 4.8,
    transactions30d: 42,
    upcomingSupply: 0,
    momChange: 1.6,
    avgDaysOnMarket: 58,
  },
  {
    slug: 'the-meadows',
    name: 'The Meadows',
    area: 'Emirates Living',
    type: 'villas',
    isFreehold: true,
    avgPricePerSqft: 1750,
    medianPrice: 5800000,
    totalUnits: 2200,
    apartments: 0,
    villas: 2200,
    grossYield: 4.1,
    transactions30d: 28,
    upcomingSupply: 0,
    momChange: 2.3,
    avgDaysOnMarket: 72,
  },
  {
    slug: 'the-lakes',
    name: 'The Lakes',
    area: 'Emirates Living',
    type: 'villas',
    isFreehold: true,
    avgPricePerSqft: 1600,
    medianPrice: 4600000,
    totalUnits: 1800,
    apartments: 0,
    villas: 1800,
    grossYield: 4.4,
    transactions30d: 22,
    upcomingSupply: 0,
    momChange: 1.8,
    avgDaysOnMarket: 65,
  },
  {
    slug: 'jumeirah-golf-estates',
    name: 'Jumeirah Golf Estates',
    area: 'West Dubai',
    type: 'villas',
    isFreehold: true,
    avgPricePerSqft: 1850,
    medianPrice: 6800000,
    totalUnits: 2400,
    apartments: 0,
    villas: 2400,
    grossYield: 3.8,
    transactions30d: 18,
    upcomingSupply: 200,
    momChange: 2.5,
    avgDaysOnMarket: 82,
  },
  {
    slug: 'jumeirah-village-triangle',
    name: 'Jumeirah Village Triangle',
    area: 'South Dubai',
    type: 'mixed',
    isFreehold: true,
    avgPricePerSqft: 980,
    medianPrice: 780000,
    totalUnits: 18000,
    apartments: 13500,
    villas: 4500,
    grossYield: 7.2,
    transactions30d: 156,
    upcomingSupply: 1800,
    momChange: 0.8,
    avgDaysOnMarket: 33,
  },
  {
    slug: 'jumeirah-park',
    name: 'Jumeirah Park',
    area: 'West Dubai',
    type: 'villas',
    isFreehold: true,
    avgPricePerSqft: 1500,
    medianPrice: 4200000,
    totalUnits: 2000,
    apartments: 0,
    villas: 2000,
    grossYield: 4.5,
    transactions30d: 32,
    upcomingSupply: 0,
    momChange: 1.4,
    avgDaysOnMarket: 60,
  },
  {
    slug: 'jumeirah-islands',
    name: 'Jumeirah Islands',
    area: 'West Dubai',
    type: 'villas',
    isFreehold: true,
    avgPricePerSqft: 2100,
    medianPrice: 8500000,
    totalUnits: 900,
    apartments: 0,
    villas: 900,
    grossYield: 3.5,
    transactions30d: 14,
    upcomingSupply: 0,
    momChange: 3.2,
    avgDaysOnMarket: 95,
  },
  {
    slug: 'port-de-la-mer',
    name: 'Port De La Mer',
    area: 'Jumeirah',
    type: 'apartments',
    isFreehold: true,
    avgPricePerSqft: 2800,
    medianPrice: 4200000,
    totalUnits: 4200,
    apartments: 4200,
    villas: 0,
    grossYield: 4.8,
    transactions30d: 48,
    upcomingSupply: 600,
    momChange: 2.9,
    avgDaysOnMarket: 52,
  },
  {
    slug: 'dubai-design-district',
    name: 'Dubai Design District',
    area: 'Central',
    type: 'apartments',
    isFreehold: true,
    avgPricePerSqft: 2200,
    medianPrice: 2800000,
    totalUnits: 3600,
    apartments: 3600,
    villas: 0,
    grossYield: 4.9,
    transactions30d: 38,
    upcomingSupply: 800,
    momChange: 2.4,
    avgDaysOnMarket: 46,
  },
  {
    slug: 'festival-city',
    name: 'Festival City',
    area: 'East Dubai',
    type: 'mixed',
    isFreehold: true,
    avgPricePerSqft: 1650,
    medianPrice: 2100000,
    totalUnits: 8400,
    apartments: 7200,
    villas: 1200,
    grossYield: 5.5,
    transactions30d: 72,
    upcomingSupply: 400,
    momChange: 1.2,
    avgDaysOnMarket: 44,
  },
  {
    slug: 'meydan',
    name: 'Meydan',
    area: 'Nad Al Sheba',
    type: 'mixed',
    isFreehold: true,
    avgPricePerSqft: 2000,
    medianPrice: 3800000,
    totalUnits: 5200,
    apartments: 3400,
    villas: 1800,
    grossYield: 5.0,
    transactions30d: 62,
    upcomingSupply: 1200,
    momChange: 2.8,
    avgDaysOnMarket: 48,
  },
  {
    slug: 'nad-al-sheba',
    name: 'Nad Al Sheba',
    area: 'Nad Al Sheba',
    type: 'mixed',
    isFreehold: true,
    avgPricePerSqft: 1550,
    medianPrice: 5200000,
    totalUnits: 3800,
    apartments: 800,
    villas: 3000,
    grossYield: 4.6,
    transactions30d: 44,
    upcomingSupply: 600,
    momChange: 1.8,
    avgDaysOnMarket: 62,
  },
  {
    slug: 'al-jaddaf',
    name: 'Al Jaddaf',
    area: 'East Dubai',
    type: 'apartments',
    isFreehold: true,
    avgPricePerSqft: 1450,
    medianPrice: 1600000,
    totalUnits: 6200,
    apartments: 6200,
    villas: 0,
    grossYield: 5.8,
    transactions30d: 56,
    upcomingSupply: 1400,
    momChange: 2.1,
    avgDaysOnMarket: 40,
  },
  {
    slug: 'dubai-investment-park',
    name: 'Dubai Investment Park',
    area: 'West Dubai',
    type: 'apartments',
    isFreehold: true,
    avgPricePerSqft: 780,
    medianPrice: 640000,
    totalUnits: 12400,
    apartments: 12400,
    villas: 0,
    grossYield: 8.6,
    transactions30d: 86,
    upcomingSupply: 600,
    momChange: 0.4,
    avgDaysOnMarket: 34,
  },
  {
    slug: 'green-community',
    name: 'Green Community',
    area: 'Dubai Investment Park',
    type: 'mixed',
    isFreehold: true,
    avgPricePerSqft: 1100,
    medianPrice: 2800000,
    totalUnits: 2400,
    apartments: 800,
    villas: 1600,
    grossYield: 5.6,
    transactions30d: 28,
    upcomingSupply: 0,
    momChange: 0.8,
    avgDaysOnMarket: 55,
  },
  {
    slug: 'the-villa',
    name: 'The Villa',
    area: 'Dubailand',
    type: 'villas',
    isFreehold: true,
    avgPricePerSqft: 1200,
    medianPrice: 3800000,
    totalUnits: 1800,
    apartments: 0,
    villas: 1800,
    grossYield: 4.9,
    transactions30d: 22,
    upcomingSupply: 0,
    momChange: 1.0,
    avgDaysOnMarket: 68,
  },
  {
    slug: 'serena',
    name: 'Serena',
    area: 'Dubailand',
    type: 'villas',
    isFreehold: true,
    avgPricePerSqft: 1150,
    medianPrice: 2600000,
    totalUnits: 2800,
    apartments: 200,
    villas: 2600,
    grossYield: 5.3,
    transactions30d: 38,
    upcomingSupply: 400,
    momChange: 1.1,
    avgDaysOnMarket: 52,
  },
  {
    slug: 'damac-hills-2',
    name: 'DAMAC Hills 2',
    area: 'Dubailand',
    type: 'mixed',
    isFreehold: true,
    avgPricePerSqft: 850,
    medianPrice: 1200000,
    totalUnits: 22000,
    apartments: 10000,
    villas: 12000,
    grossYield: 7.8,
    transactions30d: 148,
    upcomingSupply: 6200,
    momChange: 0.6,
    avgDaysOnMarket: 36,
  },
  {
    slug: 'palm-jebel-ali',
    name: 'Palm Jebel Ali',
    area: 'West Dubai',
    type: 'villas',
    isFreehold: true,
    avgPricePerSqft: 2600,
    medianPrice: 8500000,
    totalUnits: 1200,
    apartments: 0,
    villas: 1200,
    grossYield: 3.5,
    transactions30d: 32,
    upcomingSupply: 8000,
    momChange: 4.8,
    avgDaysOnMarket: 78,
  },
  {
    slug: 'jumeirah',
    name: 'Jumeirah',
    area: 'Jumeirah',
    type: 'villas',
    isFreehold: false,
    avgPricePerSqft: 1900,
    medianPrice: 8200000,
    totalUnits: 3200,
    apartments: 200,
    villas: 3000,
    grossYield: 3.8,
    transactions30d: 28,
    upcomingSupply: 0,
    momChange: 1.6,
    avgDaysOnMarket: 88,
  },
  {
    slug: 'deira',
    name: 'Deira',
    area: 'Old Dubai',
    type: 'apartments',
    isFreehold: false,
    avgPricePerSqft: 950,
    medianPrice: 680000,
    totalUnits: 42000,
    apartments: 42000,
    villas: 0,
    grossYield: 8.2,
    transactions30d: 182,
    upcomingSupply: 0,
    momChange: -0.2,
    avgDaysOnMarket: 26,
  },
  {
    slug: 'bur-dubai',
    name: 'Bur Dubai',
    area: 'Old Dubai',
    type: 'apartments',
    isFreehold: false,
    avgPricePerSqft: 1050,
    medianPrice: 780000,
    totalUnits: 28000,
    apartments: 28000,
    villas: 0,
    grossYield: 7.4,
    transactions30d: 128,
    upcomingSupply: 0,
    momChange: 0.1,
    avgDaysOnMarket: 28,
  },
  {
    slug: 'al-nahda',
    name: 'Al Nahda',
    area: 'East Dubai',
    type: 'apartments',
    isFreehold: false,
    avgPricePerSqft: 780,
    medianPrice: 520000,
    totalUnits: 18000,
    apartments: 18000,
    villas: 0,
    grossYield: 9.2,
    transactions30d: 118,
    upcomingSupply: 200,
    momChange: -0.1,
    avgDaysOnMarket: 24,
  },
  {
    slug: 'warsan',
    name: 'Warsan',
    area: 'East Dubai',
    type: 'apartments',
    isFreehold: true,
    avgPricePerSqft: 680,
    medianPrice: 480000,
    totalUnits: 14000,
    apartments: 14000,
    villas: 0,
    grossYield: 9.8,
    transactions30d: 88,
    upcomingSupply: 400,
    momChange: -0.3,
    avgDaysOnMarket: 28,
  },
  {
    slug: 'reem',
    name: 'Reem',
    area: 'Dubailand',
    type: 'villas',
    isFreehold: true,
    avgPricePerSqft: 1050,
    medianPrice: 2400000,
    totalUnits: 4200,
    apartments: 200,
    villas: 4000,
    grossYield: 5.6,
    transactions30d: 48,
    upcomingSupply: 200,
    momChange: 0.9,
    avgDaysOnMarket: 52,
  },
  {
    slug: 'living-legends',
    name: 'Living Legends',
    area: 'Dubailand',
    type: 'apartments',
    isFreehold: true,
    avgPricePerSqft: 820,
    medianPrice: 620000,
    totalUnits: 8400,
    apartments: 8400,
    villas: 0,
    grossYield: 8.0,
    transactions30d: 62,
    upcomingSupply: 0,
    momChange: 0.2,
    avgDaysOnMarket: 36,
  },
  {
    slug: 'dubai-maritime-city',
    name: 'Dubai Maritime City',
    area: 'Central',
    type: 'apartments',
    isFreehold: true,
    avgPricePerSqft: 1950,
    medianPrice: 2400000,
    totalUnits: 2800,
    apartments: 2800,
    villas: 0,
    grossYield: 5.2,
    transactions30d: 28,
    upcomingSupply: 2400,
    momChange: 3.1,
    avgDaysOnMarket: 48,
  },
  {
    slug: 'umm-suqeim',
    name: 'Umm Suqeim',
    area: 'Jumeirah',
    type: 'villas',
    isFreehold: false,
    avgPricePerSqft: 2200,
    medianPrice: 7200000,
    totalUnits: 2400,
    apartments: 200,
    villas: 2200,
    grossYield: 3.6,
    transactions30d: 18,
    upcomingSupply: 0,
    momChange: 1.9,
    avgDaysOnMarket: 82,
  },
  {
    slug: 'academic-city',
    name: 'Academic City',
    area: 'East Dubai',
    type: 'apartments',
    isFreehold: true,
    avgPricePerSqft: 760,
    medianPrice: 560000,
    totalUnits: 10800,
    apartments: 10800,
    villas: 0,
    grossYield: 8.4,
    transactions30d: 72,
    upcomingSupply: 800,
    momChange: 0.3,
    avgDaysOnMarket: 30,
  },
  {
    slug: 'al-khawaneej',
    name: 'Al Khawaneej',
    area: 'East Dubai',
    type: 'villas',
    isFreehold: false,
    avgPricePerSqft: 1100,
    medianPrice: 3800000,
    totalUnits: 2200,
    apartments: 0,
    villas: 2200,
    grossYield: 4.8,
    transactions30d: 26,
    upcomingSupply: 0,
    momChange: 0.7,
    avgDaysOnMarket: 72,
  },
]

export function getCommunityBySlug(slug: string): Community | undefined {
  return MOCK_COMMUNITIES.find(c => c.slug === slug)
}

// Generate 12 months of mock price history for charts
export function getMockPriceHistory(community: Community) {
  const months = ['Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec', 'Jan', 'Feb']
  let price = community.avgPricePerSqft * 0.88 // start ~12% below current
  return months.map((month, i) => {
    const variance = (Math.random() - 0.4) * 0.025 // slight upward bias
    price = price * (1 + variance)
    // last month = current
    if (i === 11) price = community.avgPricePerSqft
    return { month, pricePerSqft: Math.round(price) }
  })
}

// Mock recent transactions
export function getMockTransactions(community: Community) {
  const types = ['Apartment', 'Villa', 'Townhouse']
  const beds = [1, 2, 3, 4]
  return Array.from({ length: 12 }, (_, i) => {
    const sqft = 600 + Math.floor(Math.random() * 2400)
    const ppsf = community.avgPricePerSqft * (0.85 + Math.random() * 0.3)
    return {
      id: i,
      date: new Date(Date.now() - i * 2.5 * 24 * 3600 * 1000).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: '2-digit' }),
      type: community.type === 'villas' ? 'Villa' : types[Math.floor(Math.random() * (community.type === 'apartments' ? 1 : 3))],
      bedrooms: beds[Math.floor(Math.random() * beds.length)],
      sqft,
      pricePerSqft: Math.round(ppsf),
      totalPrice: Math.round(ppsf * sqft),
    }
  })
}
